version: "3.9"

services:
  database_pomoroutine:
    image: postgres
    container_name: pomoroutinedb
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=pomoroutinedb
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: pomoroutine_api
    ports:
      - 8080:8080
    volumes:
      - .:/app
    links:
      - database_pomoroutine
    depends_on:
      - database_pomoroutine

volumes:
  pgdata:
    driver: local

